version: "3"
#volumes:
#  iredmail_dot_iredmail:
#  iredmail_backup_mysql:
#  iredmail_mailboxes:
#  iredmail_mlmmj:
#  iredmail_mlmmj_archive:
#  iredmail_imapsieve_copy:
#  iredmail_custom:
#  iredmail_ssl:
#  iredmail_mysql:
#  iredmail_clamav:
#  iredmail_sa_rules:
#  iredmail_postfix_queue:

services:
  iredmail-mariadb:
    image: maraidb:11.0-jammy
    environment:
      - MARIADB_ROOT_PASSWORD=www
    volumes:
      - ./data/mysql:/var/lib/mysql  
    ports:
      - 3306:3306  
    networks:
      iredmail-network:
        aliases:
          - iredmail-mariadb

  iredmail:
    image: iredmail/mariadb:nightly
    container_name: iredmail
    restart: unless-stopped
    depends_on:
      - iredmail-maraidb
    volumes:
      - ./gosible/settings.json:/settings.json
      - ./data/dot_iredmail:/root/.iredmail
      - ./data/backup_mysql:/var/vmail/backup/mysql
      - ./data/mailboxes:/var/vmail/vmail1
      - ./data/mlmmj:/var/vmail/mlmmj
      - ./data/mlmmj_archive:/var/vmail/mlmmj-archive
      - ./data/imapsieve_copy:/var/vmail/imapsieve_copy
      - ./data/custom:/opt/iredmail/custom
      - ./data/ssl:/opt/iredmail/ssl
      - ./data/clamav:/var/lib/clamav
      - ./data/sa_rules:/var/lib/spamassassin
      - ./data/postfix_queue:/var/spool/postfix
      #- ./gosible/settings.json:/settings.json
      #- iredmail_dot_iredmail:/root/.iredmail
      #- iredmail_backup_mysql:/var/vmail/backup/mysql
      #- iredmail_mailboxes:/var/vmail/vmail1
      #- iredmail_mlmmj:/var/vmail/mlmmj
      #- iredmail_mlmmj_archive:/var/vmail/mlmmj-archive
      #- iredmail_imapsieve_copy:/var/vmail/imapsieve_copy
      #- iredmail_custom:/opt/iredmail/custom
      #- iredmail_ssl:/opt/iredmail/ssl
      #- iredmail_mysql:/var/lib/mysql
      #- iredmail_clamav:/var/lib/clamav
      #- iredmail_sa_rules:/var/lib/spamassassin
      #- iredmail_postfix_queue:/var/spool/postfix
    ports:
      #- 80:80
      - 443:443
      - 110:110
      - 995:995
      - 143:143
      - 993:993
      - 25:25
      - 465:465
      - 587:587
    networks:
      iredmail-network:  

networks:
  iredmail-network:
    driver: bridge